/*Analyze the total profit generated by each retailer */
SELECT 
    retailer,
    SUM(price_per_unit * units_sold) AS total_profit
FROM
    adidas_sales
GROUP BY
    retailer
ORDER BY
    total_profit DESC;