--1.Total Revenue by Product Type:
--Calculate the total revenue generated by each product type. This can help identify the most profitable products

select Product_type, round(sum(Revenue_generated),2) as TotalRevenue from ProductDetails 
group by Product_type
order by TotalRevenue desc 



-- 2. Shipping Costs by Carrier
-- Calculating the average shipping costs for each shipping carrier to evaluate which carrier is the most cost-effective
select Shipping_carriers, round(avg(Shipping_costs),2) as Average_Cost from Shipping 
group by Shipping_carriers;



-- 3. Total Products Sold by Location:
-- Determining the total number of products sold in each location to understand regional demand
select Location, sum(Number_of_products_sold) as Product_sold from ProductDetails p
join Shipping s 
on p.Product_id=s.Product_id
group by Location 
order by Product_sold desc;



-- 4.Defect Rates by Inspection Results:
-- The total Product and defect rates for different inspection results to assess product quality
select count(Product_id) as TotalProducts, Inspection_results, round(avg(Defect_rates), 2) defective_rate from Inspection 
group by Inspection_results
order by TotalProducts Desc



-- 5. Ranking Products by Profitability:
-- Write a query to rank products based on profitability, where profitability is calculated as (Revenue generated - Manufacturing costs - Shipping costs)
select p.Product_id, Product_type, (Revenue_generated - i.Manufacturing_costs - s.Shipping_costs) as Profitability, 
dense_rank() over(partition by  Product_type order by (Revenue_generated - i.Manufacturing_costs - s.Shipping_costs)desc ) 
as Profitability_Rank from ProductDetails p
join InventoryManagement i 
ON i.Product_id=p.Product_id
join Shipping s 
ON s.Product_id=p.Product_id



-- 6. Top 5 Shipping Carriers by Cost Efficiency:
-- Determine the top 5 shipping carriers with the lowest average shipping costs per product shipped
select p.Product_type, Shipping_carriers, avg(Shipping_costs) as avg_shippingcost, 
dense_rank() over(partition by Product_type order by avg(Shipping_costs)) as drank
from ProductDetails p
join Shipping s 
ON s.Product_id=p.Product_id
group by Shipping_carriers, Product_type;



--7.Top Best Selling Product:
SELECT Top 1
    Product_type,
    Product_id,
    Number_of_products_sold
FROM 
    ProductDetails
ORDER BY 
    Number_of_products_sold DESC



--8. Find Shipping Details for Products with Long Manufacturing Lead Time:
SELECT 
    s.Product_id,
    s.Shipping_times,
    s.Shipping_carriers,
    s.Shipping_costs,
    s.Transportation_modes,
    s.Location,i.Manufacturing_lead_time
FROM 
    Shipping s
JOIN 
    InventoryManagement i ON s.Product_id = i.Product_id
Order by 
    i.Manufacturing_lead_time desc



--9.Total Revenue for High-Value Customers and Available Stocks
SELECT 
    p.Product_type,
    sum(p.Revenue_generated) as TotalRevenue,
    p.Customer_demographics,
    sum(i.Stock_levels)as TotalStocksAvailable
FROM 
    ProductDetails p
JOIN 
    InventoryManagement i
     ON p.Product_id = i.Product_id
Group by 
p.Customer_demographics,p.Product_type,p.Customer_demographics
order by TotalRevenue desc



--10.Total Sold Product and Available Stocks by Product
SELECT
         p.Product_type, sum(p.Number_of_products_sold) as TotalSold,sum(im.Stock_levels) TotalStocksAvailable
FROM
        InventoryManagement im
JOIN ProductDetails p 
ON im.Product_id = p.Product_id
GROUP by p.Product_type
ORDER by TotalSold Desc